WebUI/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Entity;
using kutuphane.Data.Abstract;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class BookController : Controller
    {
        private IBookRepository bookRepository;
        private ITypeRepository typeRepository;
        private IAuthorRepository authorRepository;
        private IPublisherRepository publisherRepository;
        private ILanguageRepository languageRepository;
        public BookController(ILanguageRepository _languageRepo,IPublisherRepository _publisherRepo, IBookRepository _bookRepo,ITypeRepository _typeRepo,IAuthorRepository _authRepo)
        {
            bookRepository = _bookRepo;
            typeRepository = _typeRepo;
            authorRepository= _authRepo;
            publisherRepository = _publisherRepo;
            languageRepository = _languageRepo;
        }
        public IActionResult AddFavorite(int id)
        {
          var book = bookRepository.GetById(id);
          bookRepository.AddFav(book);
          TempData["successmessage"] = $" \"{book.Name}\" added favorite list.";
          return RedirectToAction("Details", new {@id=id});
        }
        public IActionResult RemoveFavorite(int id)
        {
           var book = bookRepository.GetById(id);
          bookRepository.RemoveFav(book);
          TempData["failmessage"] = $"\"{book.Name}\" removed favorite list.";
          return RedirectToAction("Details", new {@id=id});
        }
       
        public IActionResult List()
        {
             BookModel model = new BookModel();
                model.BookList = bookRepository.GetAll().ToList();         
                model.AuthorList = authorRepository.GetAll().ToList();
                model.TypeList = typeRepository.GetAll().ToList();
          return View(model);
        }
        public IActionResult Index(int? id,string q)
        {
            var query = bookRepository.GetAll()
                .Where(i => i.isApproved);
            if (id != null)
            {
                query = query.Where(i => i.TypeId==id);
             
                
            } 
            if (!string.IsNullOrEmpty(q))
            {
              var aid=0;
             var aut = authorRepository.GetAll().Where(i => EF.Functions.Like(i.Name,"%"+q+"%") || EF.Functions.Like(i.Surname,"%"+q+"%")).ToList();
             foreach (var item in aut)
             {
                 aid = item.Id;
             }
              
                query = query.Where( i =>
                  EF.Functions.Like(i.Name,"%"+q+"%") ||
                  i.AuthorId == aid
                );
            } 
             
          return View(query);
        }

        public void pullSelect()
        {
             var author = authorRepository.GetAll()
                .Where(x => x.isApproved)
                .Select(x => new
                {
                    selectname =x.Id,
                    fullname = x.Name+" "+x.Surname
                });
            ViewBag.Types = new SelectList(typeRepository.GetAll(),"TypeId","Name");
            ViewBag.Authors = new SelectList(author,"selectname", "fullname");
            ViewBag.Publisher = new SelectList(publisherRepository.GetAll(),"PublisherId","Name");
            ViewBag.Language = new SelectList(languageRepository.GetAll(),"LanguageId","Name");
        }
      
        [HttpGet]
        public IActionResult Create()
        {
           pullSelect();
          return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Book entity,IFormFile file)
        {
          
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot\\img",file.FileName);
                    using (var stream = new FileStream(path,FileMode.Create))
                    {
                      await file.CopyToAsync(stream);			
                      entity.Image=file.FileName;
                    }
                }
                bookRepository.SaveBook(entity);
                return RedirectToAction("List");
            }
            pullSelect();
          return View(entity);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {         
          return View(bookRepository.GetById(id));
        }
        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirmed(int BookId)
        {
        bookRepository.DeleteBook(BookId);
          return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
          pullSelect();
          return View(bookRepository.GetById(id));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Book entity,IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {					
                    var path = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot\\img",file.FileName);

                    using (var stream = new FileStream(path,FileMode.Create))
                    {
                        await file.CopyToAsync(stream);			
                        entity.Image=file.FileName;
                    }
                }
                bookRepository.SaveBook(entity);
                return RedirectToAction("List");
            }
            pullSelect();
            return View(entity);
        }
        public IActionResult Details(int id)
        {
          dynamic model = new ExpandoObject();
                model.BookList = bookRepository.GetById(id);         
                model.AuthorList = authorRepository.GetById(model.BookList.AuthorId);
                model.TypeList = typeRepository.GetById(model.BookList.TypeId);
                model.PublisherList = publisherRepository.GetById(model.BookList.PublisherId);
                model.LanguageList = languageRepository.GetById(model.BookList.LanguageId);
          return View(model);
        }

        public IActionResult MarkRead(int id)
        {
          var book = bookRepository.GetById(id);
          bookRepository.MarkRead(book);
          TempData["successmessage"] = $" \"{book.Name}\" marked as read.";
          return RedirectToAction("Details", new {@id=id});
        }
        public IActionResult MarkUnread(int id)
        {
           var book = bookRepository.GetById(id);
          bookRepository.MarkUnread(book);
          TempData["failmessage"] = $"\"{book.Name}\" marked unread.";
            return RedirectToAction("Details", new {@id=id});
        }
       
    }

}

WebUI/ViewComponents/TypeMenuViewComponent.cs
using kutuphane.Data.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace kutuphane.WebUI.ViewComponents
{
    public class TypeMenuViewComponent : ViewComponent
    {
        private ITypeRepository _repository;
        public TypeMenuViewComponent(ITypeRepository repo)
        {
            _repository = repo;            
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["id"];
            return View(_repository.GetAll());
        }
    }
}

WebUI/Views/Book/Create.cshtml
@model Book
@{
ViewData["Title"] = "Book Create Page";
}
@section scripts{
<script src="https://cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script>
<script>
	CKEDITOR.replace("Abstract");
</script>
}
<div class="container-fluid">
	<form asp-action="Create" asp-controller="Book" method="POST" enctype="multipart/form-data">
	
		<div class="form-group">
			<label asp-for="Name">Name</label>
			<div ><span class="text-danger" asp-validation-for="Name"></span></div>	
			<input asp-for="Name" class="form-control" placeholder="Please enter book name.">
		</div>
		
		<div class="form-group">
			<label asp-for="Page">Page Count</label>
			<div ><span class="text-danger" asp-validation-for="Page"></span></div>	
			<input asp-for="Page" class="form-control" placeholder="Please enter page.">
		</div>
		<div class="form-group">
			<label asp-for="PublisherId">Publisher</label>
			<select class="form-control" asp-for="PublisherId" asp-items="ViewBag.Publisher">
				<option  disabled selected value="">Select Publisher...</option>
				
			</select>
		</div>
		<div class="form-group">
			<label asp-for="Abstract">Abstract</label>
			<textarea asp-for="Abstract" class="form-control"></textarea>
		</div>		
		
		<div class="form-group w-25" >
			<label asp-for="PublishDate">Publish Date</label>
			<input asp-for="PublishDate" id="datepicker"  />
		</div>

		<div class="form-group">
			<label asp-for="LanguageId">Language</label>
			<select class="form-control" asp-for="LanguageId" asp-items="ViewBag.Language">
				<option  disabled selected value="">Select Language...</option>
				
			</select>
		</div>
		<div class="form-group">
			<label asp-for="AuthorId">Author</label>
			<select class="form-control" asp-for="AuthorId" asp-items="ViewBag.Authors">
				<option  disabled selected value="">Select Author...</option>
				
			</select>
		</div>
		<div class="form-group">
			<label asp-for="TypeId">Type</label>
			<select class="form-control" asp-for="TypeId" asp-items="ViewBag.Types">
				<option disabled selected value="">Select Type...</option>
				
			</select>
		</div>

		<div class="custom-file">
			<img src="" width="120" alt="" >
			<input type="file" class="custom-file-input" name="file" id="file">
			<label class="custom-file-label" for="file">Choose file...</label>
		</div>

		<div class=" form-group form-check">
			<label class="form-check-label" asp-for="isApproved">
				<input class="form-check-input" asp-for="isApproved">
				Görüntülensin mi ?
			</label>
		</div>
		<button type="submit" class="btn btn-primary">Create</button>
	</form>
</div>

WebUI/Views/Book/Delete.cshtml
@model Book
@{
ViewData["Title"] = "Delete";
}

<h2>
    <b>@Model.Name</b> isimli kaydı silmek istiyormusunuz ?

</h2>
<form asp-controller="Book" asp-action="Delete" method="POST">
    <input type="hidden" asp-for="BookId">
    <button type="submit" class="btn btn-primary">Delete</button>
</form>

WebUI/Views/Book/Details.cshtml
@model dynamic  
@{
ViewData["Title"] = "Detail Book ";
}


<div class="jumbotron jumbotron-fluid">
	<div class="container">
		<h1 class="display-4">@Model.BookList.Name</h1>
		<p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<div class=" w-100 " role="group" >
                
                @if (@Model.BookList.isReaded==true)
                {
                    <a class="btn btn-block m-0" asp-action="MarkUnread" asp-controller="Book" asp-route-id="@Model.BookList.BookId"  title="Mark as the unread"><i class="fas fa-bookmark text-success"></i> Mark as Unread</a>
                }
                else
                {
                    <a class="btn btn-block m-0" asp-action="MarkRead" asp-controller="Book" asp-route-id="@Model.BookList.BookId" title="Mark as the read" ><i class="far fa-bookmark text-success"></i> Mark as Read</a>
                }
				@if (@Model.BookList.isFavorite==true)
                {
                    <a class="btn btn-block m-0" asp-action="RemoveFavorite" asp-controller="Book" asp-route-id="@Model.BookList.BookId"  title="Remove the favorite"><i class="fas fa-star text-warning "></i> Remove Favorite</a>
                }
                else
                {
                    <a class="btn btn-block m-0" asp-action="AddFavorite" asp-controller="Book" asp-route-id="@Model.BookList.BookId" title="Add the favorite" ><i class="far fa-star text-warning"></i> Add Favorite</a>
                }
                
			</div>
			
			
			<img style="width:100%;" src="~/img/@Model.BookList.Image" alt="@Model.BookList.Name">
		</div>
		<div class="col-md-8">
			<table class="table table-sm table-bordered table-striped">                       
				<tr>
					<th>Name</th>
					<td>@Model.BookList.Name</td>
				</tr>
				<tr>
					<th>Page Count</th>
					<td>@Model.BookList.PageCount</td>
				</tr>
				<tr>
					<th>Author</th>
					<td>@(Model.AuthorList.Name+ " " + Model.AuthorList.Surname)</td>
				</tr>
				<tr>
					<th>Type</th>
					<td>@Model.TypeList.Name</td>
				</tr>
				<tr>
					<th>Language</th>
					<td>@Model.LanguageList.Name</td>
				</tr>
				<tr>
					<th>Publisher</th>
					<td>@Model.PublisherList.Name</td>
				</tr>
				<tr>
					<th>Publish Date</th>
					<td>@Model.BookList.PublishDate.ToString("MMMM dd, yyyy")</td>
				</tr>
			</table>
			
			<p class="h5">Abstract</p>
			<p>@Html.Raw(@Model.BookList.Abstract)</p>
		</div>
		
	</div>
</div>

WebUI/Views/Book/Edit.cshtml
@model Book
@{
ViewData["Title"] = "Edit Book ";
}
<div class="container">
    
<form asp-action="Edit" asp-controller="Book" method="POST" enctype="multipart/form-data">
    <input type="hidden" asp-for="BookId">
    <input type="hidden" asp-for="Image">
 	<div class="form-group">
			<label asp-for="Name">Name</label>
			<input asp-for="Name" class="form-control" placeholder="Please enter book name.">
		</div>
		
		<div class="form-group">
      <div class="row">
        <div class="col-md-6">
          	<label asp-for="Page">Page</label>
			<input asp-for="Page" class="form-control" placeholder="Please enter page.">

        </div>
        <div class="col-md-6">
          	<label asp-for="PublisherId">Publisher</label>
			<select class="form-control" asp-for="PublisherId" asp-items="ViewBag.Publisher">
				<option  disabled selected value="">Select Publisher...</option>
				
			</select>
        </div>
      </div>
		
		</div>
	
		<div class="form-group">
			<label asp-for="Abstract">Abstract</label>
			<textarea asp-for="Abstract" class="form-control"></textarea>
		</div>		
		
		<div class="form-group" >
      <div class="row">
        <div class="col-md-6">
          	<label asp-for="PublishDate">Publish Date</label>
			<input asp-format="{0:dd/MM/yyyy}" asp-for="PublishDate" id="datepicker"  />
        </div>
        <div class="col-md-6">
          	<label asp-for="TypeId">Type</label>
			<select class="form-control" asp-for="TypeId" asp-items="ViewBag.Types">
				<option disabled selected value="">Select Type...</option>
				
			</select>
        </div>
      </div>
		
		</div>

		<div class="form-group">
      <div class="row">      
      <div class="col-md-6">
        <label asp-for="LanguageId">Language</label>
		  	<select class="form-control" asp-for="LanguageId" asp-items="ViewBag.Language">
				<option  disabled selected value="">Select Language...</option>				
			</select>
      </div>
      <div class="col-md-6">
          <label asp-for="AuthorId">Author</label>
			    <select class="form-control" asp-for="AuthorId" asp-items="ViewBag.Authors">
				    <option  disabled selected value="">Select Author...</option>
				
		    	</select>
      </div>
			</div>
		</div>

  <div class="form-group">
    <div class="row">
      <div class="col-md-2 text-center">
    	    <img src="~/img/@Model.Image" width="120" alt="@Model.Name" >
      </div>
      <div class="col-md-10 m-auto">
          <div class="custom-file">
			<input type="file" class="custom-file-input" name="file" id="file">
			<label class="custom-file-label" for="file">Choose file...</label>
		
		</div>
      </div>
    </div>
  </div>
		

		<div class=" form-group form-check">
			<label class="form-check-label" asp-for="isApproved">
				<input class="form-check-input" asp-for="isApproved">
				Görüntülensin mi ?
			</label>
		</div>
		<button type="submit" class="btn btn-primary">Save</button>
</form>
</div>

WebUI/Views/Book/Index.cshtml
@model IEnumerable<Book>
@{
    ViewData["Title"] = "Home Page";
}
<div class="container my-4">
  <div class="row">
      <div class="col-md-3">
        @await Component.InvokeAsync("TypeMenu")
      </div>
    <div class="col-md-9">
      <partial name="_HomeList" model="Model" />
        
    </div>
  </div>
</div>

WebUI/Views/Book/List.cshtml
@model BookModel
@{
ViewData["Title"] = "Book List Page";
}


<div class="container my-4">
    <div class="row">
        <div class="col-md-3">
        <partial name="_PanelMenu" />
        </div>
        <div class="col-md-9">
            
                <div class="row">
                      
                    <div class="col">
                        <div class="text-right mb-3">
                            <a href="/book/create" class="btn btn-sm btn-primary">Create</a>
                        </div>
                        @if (Model.BookList.Count()>0)
                        {
                            <table class="table table-bordered table-striped">
                                <thead>
                                    <th>Id</th>
                                    <th>Image</th>
                                    <th>Name</th>
                                    <th>Author</th>
                                    <th>Approved</th>
                                    <th></th>

                                </thead>
                                <tbody>
                                @foreach (var item in Model.BookList)
                                {
                                    <tr>
                                        <td>@item.BookId</td>
                                        <td>
                                            <img height="100px;" src="~/img/@item.Image" alt="@item.Name">                                
                                        </td>
                                        <td>@item.Name</td>
                                        <td>
                                            @foreach (var author in Model.AuthorList)
                                            {
                                                @if (author.Id == item.AuthorId)
                                                {
                                                    @(author.Name+" "+ author.Surname)
                                                }
                                            }                                           
                                        </td>
                                        <td>
                                            @if (@item.isApproved)
                                            {
                                                <span class="badge badge-success">Yes</span>
                                            }
                                            else
                                            {
                                                <span class="badge badge-danger">No</span>
                                            }
                                        </td>
                                        <td>
                                              <a class="btn btn-success btn-sm" asp-route-id="@item.BookId" asp-action="Details" asp-controller="Book">
                                                    Detail</a>
                                            <a class="btn btn-primary btn-sm" asp-route-id="@item.BookId" asp-action="Edit" asp-controller="Book">
                                                    Edit</a>
                                                <a class="btn btn-danger btn-sm" asp-route-id="@item.BookId" asp-action="Delete" asp-controller="Book">Delete</a>
                                        </td>
                                    </tr>
                                }
                                </tbody>
                            </table>
                        }
                        else
                        {
                        <div class="alert alert-danger">
                            Kitap Bulunamadı.
                        </div>
                        }
                </div>
            
        </div>        
    </div>        
</div>