WebUI/Controllers/PublisherController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Entity;
using kutuphane.Data.Abstract;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class PublisherController : Controller
    {
        private IPublisherRepository publisherRepository;
        public PublisherController(IPublisherRepository _publisherRepo)
        {
            publisherRepository = _publisherRepo;
        }
        public IActionResult List()
        {          
          return View(publisherRepository.GetAll());
        }
        [HttpGet]
        public IActionResult Create()
        {         
          return View();
        }
        [HttpPost]
        public IActionResult Create(Entity.Publisher entity)
        {
            if (ModelState.IsValid)
            {
                publisherRepository.SavePublisher(entity);
                return RedirectToAction("List");
            }
            return View(entity);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {         
          return View(publisherRepository.GetById(id));
        }
        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirmed(int PublisherId)
        {
          publisherRepository.DeletePublisher(PublisherId);
          return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
         
          return View(publisherRepository.GetById(id));
        }
        [HttpPost]
        public IActionResult Edit(Entity.Publisher entity)
        {
          if (ModelState.IsValid)
          {
              publisherRepository.SavePublisher(entity);
              return RedirectToAction("List");
          }
          return View(entity);
        }
        public IActionResult Details(int id)
        {
          
          return View(publisherRepository.GetById(id));
        }
    }

}

WebUI/Views/Publisher/Create.cshtml
@model Entity.Publisher
@{
    ViewData["Title"] = "Publisher Create Page";
}

<form asp-action="Create" asp-controller="Publisher" method="POST" >
 <div class="form-group">
   <label asp-for="Name">Name</label>
    <input asp-for="Name" class="form-control" placeholder="Please enter publisher name.">

  </div>
<button type="submit" class="btn btn-primary">Create</button>
</form>

WebUI/Views/Publisher/Delete.cshtml
@model Entity.Publisher
@{
ViewData["Title"] = "Delete Publisher";
}

<h2>
    <b>@Model.Name</b> isimli türü silmek istiyormusunuz ?

</h2>
<form asp-controller="Publisher" asp-action="Delete" method="POST">
    <input type="hidden" asp-for="PublisherId">
    <button type="submit" class="btn btn-primary">Delete</button>
</form>

WebUI/Views/Publisher/Details.cshtml
@model Entity.Publisher
@{
ViewData["Title"] = "Detail Publisher ";
}


<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">@Model.Name</h1>
        <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
    </div>
</div>
<div class="container">
    <div class="row">       
        <div class="col-md-12">
           <table class="table table-sm table-bordered table-striped">          
                <tr>
                    <th>Name</th>
                    <td>@Model.Name</td>
                </tr>               
                
           </table>
         
        </div>
        
    </div>
</div>

WebUI/Views/Publisher/Edit.cshtml
@model Entity.Publisher
@{
ViewData["Title"] = "Edit Publisher ";
}
<div class="container">
    
<form asp-action="Edit" asp-controller="Publisher" method="POST" >
    <input type="hidden" asp-for="PublisherId">
 <div class="form-group">
   <label asp-for="Name">Name</label>
    <input asp-for="Name" class="form-control" placeholder="Please enter publisher name.">
  </div>
  
 
<button type="submit" class="btn btn-primary">Save</button>
</form>
</div>

WebUI/Views/Publisher/List.cshtml
@model IEnumerable<Entity.Publisher>
@{
ViewData["Title"] = "Publisher List Page";
}


<div class="container my-4">
    <div class="row">
        <div class="col-md-3">
        <partial name="_PanelMenu" />
        </div>
        <div class="col-md-9">
           
                <div class="row">
                     
                    <div class="col">
                        <div class="text-right mb-3">
                            <a href="/publisher/create" class="btn btn-sm btn-primary">Create</a>
                        </div>
                        @if (Model.Count()>0)
                        {
                            <table class="table table-bordered table-striped">
                                <thead>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th></th>

                                </thead>
                                <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.PublisherId</td>                                       
                                        <td>@item.Name</td>
                                        <td>
                                            <a class="btn btn-success btn-sm" asp-route-id="@item.PublisherId" asp-action="Details" asp-controller="Publisher">
                                                    Detail</a>
                                            <a class="btn btn-primary btn-sm" asp-route-id="@item.PublisherId" asp-action="Edit" asp-controller="Publisher">
                                                    Edit</a>
                                            <a class="btn btn-danger btn-sm" asp-route-id="@item.PublisherId" asp-action="Delete" asp-controller="Publisher">Delete</a>
                                        </td>
                                    </tr>
                                }
                                </tbody>
                            </table>
                        }
                        else
                        {
                        <div class="alert alert-danger">
                            Not found Publisher.
                        </div>
                        }
                </div>
            
        </div>        
    </div>        
</div>