WebUI/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Entity;
using kutuphane.Data.Abstract;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class LanguageController : Controller
    {
        private ILanguageRepository languageRepository;
        public LanguageController(ILanguageRepository _languageRepo)
        {
            languageRepository = _languageRepo;
        }
        public IActionResult List()
        {          
          return View(languageRepository.GetAll());
        }
        [HttpGet]
        public IActionResult Create()
        {         
          return View();
        }
        [HttpPost]
        public IActionResult Create(Entity.Language entity)
        {
            if (ModelState.IsValid)
            {
                languageRepository.SaveLanguage(entity);
                return RedirectToAction("List");
            }
            return View(entity);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {         
          return View(languageRepository.GetById(id));
        }
        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirmed(int LanguageId)
        {
          languageRepository.DeleteLanguage(LanguageId);
          return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
         
          return View(languageRepository.GetById(id));
        }
        [HttpPost]
        public IActionResult Edit(Entity.Language entity)
        {
          if (ModelState.IsValid)
          {
              languageRepository.SaveLanguage(entity);
              return RedirectToAction("List");
          }
          return View(entity);
        }
        public IActionResult Details(int id)
        {
          
          return View(languageRepository.GetById(id));
        }
    }

}

WebUI/Views/Language/Create.cshtml
@model Entity.Language
@{
    ViewData["Title"] = "Language Create Page";
}

<form asp-action="Create" asp-controller="Language" method="POST" >
   <div class="form-group">
   <label asp-for="Code">Code</label>
    <input asp-for="Code" class="form-control" placeholder="Please enter language code.">
  </div>
 <div class="form-group">
   <label asp-for="Name">Name</label>
    <input asp-for="Name" class="form-control" placeholder="Please enter language name.">

  </div>
<button type="submit" class="btn btn-primary">Create</button>
</form>

WebUI/Views/Language/Delete.cshtml
@model Entity.Language
@{
ViewData["Title"] = "Delete Language";
}

<h2>
    <b>@Model.Name</b> isimli dili silmek istiyormusunuz ?

</h2>
<form asp-controller="Language" asp-action="Delete" method="POST">
    <input type="hidden" asp-for="LanguageId">
    <button type="submit" class="btn btn-primary">Delete</button>
</form>

WebUI/Views/Language/Details.cshtml
@model Entity.Language
@{
ViewData["Title"] = "Detail Language ";
}


<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">@Model.Name</h1>
        <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
    </div>
</div>
<div class="container">
    <div class="row">       
        <div class="col-md-12">
           <table class="table table-sm table-bordered table-striped">   
                 <tr>
                    <th>Code</th>
                    <td>@Model.Code</td>
                </tr>          
                <tr>
                    <th>Name</th>
                    <td>@Model.Name</td>
                </tr>               
                
           </table>
         
        </div>
        
    </div>
</div>

WebUI/Views/Language/Edit.cshtml
@model Entity.Language
@{
ViewData["Title"] = "Edit Language ";
}
<div class="container">
    
<form asp-action="Edit" asp-controller="Language" method="POST" >
    <input type="hidden" asp-for="LanguageId">
     <div class="form-group">
   <label asp-for="Code">Code</label>
    <input asp-for="Code" class="form-control" placeholder="Please enter language Code.">
  </div>
 <div class="form-group">
   <label asp-for="Name">Name</label>
    <input asp-for="Name" class="form-control" placeholder="Please enter language name.">
  </div>
  
 
<button type="submit" class="btn btn-primary">Save</button>
</form>
</div>

WebUI/Views/Language/List.cshtml
@model IEnumerable<Entity.Language>
@{
ViewData["Title"] = "Language List Page";
}


<div class="container my-4">
    <div class="row">
        <div class="col-md-3">
        <partial name="_PanelMenu" />
        </div>
        <div class="col-md-9">
            
                <div class="row">
                    
                    <div class="col">
                         <div class="text-right mb-3">
                            <a href="/language/create" class="btn btn-sm btn-primary">Create</a>
                        </div>
                        @if (Model.Count()>0)
                        {
                            <table class="table table-bordered table-striped">
                                <thead>
                                    <th>Id</th>
                                    <th>Code</th>
                                    <th>Name</th>
                                    <th></th>

                                </thead>
                                <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.LanguageId</td>                                       
                                        <td>@item.Code</td>                                       
                                        <td>@item.Name</td>
                                        <td>
                                            <a class="btn btn-success btn-sm" asp-route-id="@item.LanguageId" asp-action="Details" asp-controller="Language">
                                                    Detail</a>
                                            <a class="btn btn-primary btn-sm" asp-route-id="@item.LanguageId" asp-action="Edit" asp-controller="Language">
                                                    Edit</a>
                                            <a class="btn btn-danger btn-sm" asp-route-id="@item.LanguageId" asp-action="Delete" asp-controller="Language">Delete</a>
                                        </td>
                                    </tr>
                                }
                                </tbody>
                            </table>
                        }
                        else
                        {
                        <div class="alert alert-danger">
                            Not language
                        </div>
                        }
                </div>
            
        </div>        
    </div>        
</div>

 