WebUI/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Entity;
using kutuphane.Data.Abstract;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class AuthorController : Controller
    {
        private IAuthorRepository authorRepository;
        private IBookRepository bookRepository;
        private ITypeRepository typeRepository;
        public AuthorController(IAuthorRepository _authRepo,IBookRepository _bookRepo,ITypeRepository _typeRepo)
        {
            authorRepository = _authRepo;
            bookRepository = _bookRepo;
            typeRepository = _typeRepo;
        }
        public IActionResult List()
        {          
          return View(authorRepository.GetAll());
        }
        [HttpGet]
        public IActionResult Create()
        {         
          return View();
        }
        [HttpPost]
        public IActionResult Create(Author entity)
        {
            if (ModelState.IsValid)
            {
                authorRepository.SaveAuthor(entity);
                return RedirectToAction("List");
            }
            return View(entity);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {         
          return View(authorRepository.GetById(id));
        }
        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirmed(int AuthorId)
        {
          authorRepository.DeleteAuthor(AuthorId);
          return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
         
          return View(authorRepository.GetById(id));
        }
        [HttpPost]
        public IActionResult Edit(Author entity)
        {
          if (ModelState.IsValid)
          {
              authorRepository.SaveAuthor(entity);
              return RedirectToAction("List");
          }
          return View(entity);
        }
        
        public IActionResult Details(int id)
        {         
          return View(authorRepository.GetById(id));
       
        }
    }

}

WebUI/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Entity;
using kutuphane.Data.Abstract;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class BookController : Controller
    {
        private IBookRepository bookRepository;
        private ITypeRepository typeRepository;
        private IAuthorRepository authorRepository;
        private IPublisherRepository publisherRepository;
        private ILanguageRepository languageRepository;
        public BookController(ILanguageRepository _languageRepo,IPublisherRepository _publisherRepo, IBookRepository _bookRepo,ITypeRepository _typeRepo,IAuthorRepository _authRepo)
        {
            bookRepository = _bookRepo;
            typeRepository = _typeRepo;
            authorRepository= _authRepo;
            publisherRepository = _publisherRepo;
            languageRepository = _languageRepo;
        }
        public IActionResult AddFavorite(int id)
        {
          var book = bookRepository.GetById(id);
          bookRepository.AddFav(book);
          TempData["successmessage"] = $" \"{book.Name}\" added favorite list.";
          return RedirectToAction("Details", new {@id=id});
        }
        public IActionResult RemoveFavorite(int id)
        {
           var book = bookRepository.GetById(id);
          bookRepository.RemoveFav(book);
          TempData["failmessage"] = $"\"{book.Name}\" removed favorite list.";
          return RedirectToAction("Details", new {@id=id});
        }
       
        public IActionResult List()
        {
             BookModel model = new BookModel();
                model.BookList = bookRepository.GetAll().ToList();         
                model.AuthorList = authorRepository.GetAll().ToList();
                model.TypeList = typeRepository.GetAll().ToList();
          return View(model);
        }
        public IActionResult Index(int? id,string q)
        {
            var query = bookRepository.GetAll()
                .Where(i => i.isApproved);
            if (id != null)
            {
                query = query.Where(i => i.TypeId==id);
             
                
            } 
            if (!string.IsNullOrEmpty(q))
            {
              var aid=0;
             var aut = authorRepository.GetAll().Where(i => EF.Functions.Like(i.Name,"%"+q+"%") || EF.Functions.Like(i.Surname,"%"+q+"%")).ToList();
             foreach (var item in aut)
             {
                 aid = item.Id;
             }
              
                query = query.Where( i =>
                  EF.Functions.Like(i.Name,"%"+q+"%") ||
                  i.AuthorId == aid
                );
            } 
             
          return View(query);
        }

        public void pullSelect()
        {
             var author = authorRepository.GetAll()
                .Where(x => x.isApproved)
                .Select(x => new
                {
                    selectname =x.Id,
                    fullname = x.Name+" "+x.Surname
                });
            ViewBag.Types = new SelectList(typeRepository.GetAll(),"TypeId","Name");
            ViewBag.Authors = new SelectList(author,"selectname", "fullname");
            ViewBag.Publisher = new SelectList(publisherRepository.GetAll(),"PublisherId","Name");
            ViewBag.Language = new SelectList(languageRepository.GetAll(),"LanguageId","Name");
        }
      
        [HttpGet]
        public IActionResult Create()
        {
           pullSelect();
          return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Book entity,IFormFile file)
        {
          
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot\\img",file.FileName);
                    using (var stream = new FileStream(path,FileMode.Create))
                    {
                      await file.CopyToAsync(stream);			
                      entity.Image=file.FileName;
                    }
                }
                bookRepository.SaveBook(entity);
                return RedirectToAction("List");
            }
            pullSelect();
          return View(entity);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {         
          return View(bookRepository.GetById(id));
        }
        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirmed(int BookId)
        {
        bookRepository.DeleteBook(BookId);
          return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
          pullSelect();
          return View(bookRepository.GetById(id));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Book entity,IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {					
                    var path = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot\\img",file.FileName);

                    using (var stream = new FileStream(path,FileMode.Create))
                    {
                        await file.CopyToAsync(stream);			
                        entity.Image=file.FileName;
                    }
                }
                bookRepository.SaveBook(entity);
                return RedirectToAction("List");
            }
            pullSelect();
            return View(entity);
        }
        public IActionResult Details(int id)
        {
          dynamic model = new ExpandoObject();
                model.BookList = bookRepository.GetById(id);         
                model.AuthorList = authorRepository.GetById(model.BookList.AuthorId);
                model.TypeList = typeRepository.GetById(model.BookList.TypeId);
                model.PublisherList = publisherRepository.GetById(model.BookList.PublisherId);
                model.LanguageList = languageRepository.GetById(model.BookList.LanguageId);
          return View(model);
        }

        public IActionResult MarkRead(int id)
        {
          var book = bookRepository.GetById(id);
          bookRepository.MarkRead(book);
          TempData["successmessage"] = $" \"{book.Name}\" marked as read.";
          return RedirectToAction("Details", new {@id=id});
        }
        public IActionResult MarkUnread(int id)
        {
           var book = bookRepository.GetById(id);
          bookRepository.MarkUnread(book);
          TempData["failmessage"] = $"\"{book.Name}\" marked unread.";
            return RedirectToAction("Details", new {@id=id});
        }
       
    }

}

WebUI/Controllers/TypeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Entity;
using kutuphane.Data.Abstract;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class TypeController : Controller
    {
        private ITypeRepository typeRepository;
        public TypeController(ITypeRepository _typeRepo)
        {
            typeRepository = _typeRepo;
        }
        public IActionResult List()
        {          
          return View(typeRepository.GetAll());
        }
        [HttpGet]
        public IActionResult Create()
        {         
          return View();
        }
        [HttpPost]
        public IActionResult Create(Entity.Type entity)
        {
            if (ModelState.IsValid)
            {
                typeRepository.SaveType(entity);
                return RedirectToAction("List");
            }
            return View(entity);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {         
          return View(typeRepository.GetById(id));
        }
        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirmed(int TypeId)
        {
          typeRepository.DeleteType(TypeId);
          return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
         
          return View(typeRepository.GetById(id));
        }
        [HttpPost]
        public IActionResult Edit(Entity.Type entity)
        {
          if (ModelState.IsValid)
          {
              typeRepository.SaveType(entity);
              return RedirectToAction("List");
          }
          return View(entity);
        }
        public IActionResult Details(int id)
        {
          
          return View(typeRepository.GetById(id));
        }
    }

}

WebUI/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using kutuphane.Data.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class UserController : Controller
    {
        private IUserRepository userRepository;
        private IBookRepository bookRepository;
        private ITypeRepository typeRepository;
        public UserController(IUserRepository _userRepo,IBookRepository _bookRepo,ITypeRepository _typeRepo)
        {
            userRepository = _userRepo;
            bookRepository = _bookRepo;
            typeRepository = _typeRepo;
        }
        public IActionResult Index()
        {
            return View(userRepository.GetAll());
        }

        public IActionResult Read()
        {
            
          return View(bookRepository.GetAll().Where(i => !i.isReaded));
        }

        public IActionResult Unread()
        {
          return View(bookRepository.GetAll().Where(i => i.isReaded));
        }
        public IActionResult Favorites()
        {
        
          return View(bookRepository.GetAll().Where(i => i.isFavorite));
        }

      
    }
}

WebUI/Views/Shared/_HomeList.cshtml
 
@model IEnumerable<Entity.Book>

<h6> <strong>@Model.Count() </strong> results found.</h6>   

@if (Model.Count() == 0)
{
	<div class="alert alert-warning">
		Kayıt Yok
	</div>
}
else
{    


	@foreach (var item in Model)
	{
    <div class="card mb-12 mb-3" style="max-height: 400px;" >
        <div class="row no-gutters">
            <div class="col-md-4">
                <a asp-controller="Book" asp-action="Details" asp-route-id="@item.BookId">
                    <img src="~/img/@item.Image" class="card-img" alt="@item.Name" style="height: 400px;">
                </a>

            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <div class="pl-2">                       
                        <div class="row">
                            <h4 class="card-title">@item.Name</h4>
                            <p class="card-text card-abstract">@item.Abstract</p>   
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>	
    }
}

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebUI</title>
       <script src="~/lib/jquery/dist/jquery.min.js"></script>
     
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gijgo/1.9.13/combined/css/gijgo.min.css" integrity="sha256-bH0WSMuCFoG/dxeox/5aOWmaZl729yDg4ylckwSRTfU=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Library</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      
     <li class="nav-item">
        <a class="nav-link" href="/panel" >
          Panel
        </a>        
      </li>
     <li class="nav-item">
        <a class="nav-link" href="/statistics" >
          Statistics
        </a>        
      </li>
    </ul>
   <partial name="_SearchBox" />

     <a class="btn btn-outline-light ml-3 rounded-circle" asp-action="Index" asp-controller="User"><i class="far fa-user"></i></a>  
  
  </div>
</nav>
    </header>

    <div class="container mt-4">
        <main role="main" class="pb-3">
          <div class="container">
					@if (TempData["successmessage"] != null)
				  {
					 <div class="alert alert-success">
						 @TempData["successmessage"]
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
					 </div>
				  }
          else if (TempData["failmessage"] != null)
				  {
					 <div class="alert alert-danger">
						 @TempData["failmessage"]
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
					 </div>
				  }
			</div>
            @RenderBody()
        </main>
    </div>

 
 
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gijgo/1.9.13/combined/js/gijgo.min.js" integrity="sha256-YZhUu69bCn9uTqQyKwwQ3GyRypS7eaxp/wmVS282sDI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
    @RenderSection("scripts",false)
  <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
     
    <script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>

WebUI/Views/Shared/_PanelMenu.cshtml
<div class="list-group">             
    <a asp-controller="Book" asp-action="List" class="list-group-item"><i class="fas fa-book"></i> Book Options </a>
    <a asp-controller="Author" asp-action="List" class="list-group-item"><i class="fas fa-feather"></i> Author Options </a>
    <a asp-controller="Type" asp-action="List" class="list-group-item"><i class="fas fa-list"></i> Type Options </a>       
    <a asp-controller="Publisher" asp-action="List" class="list-group-item"><i class="fas fa-bullhorn"></i> Publisher Options </a>       
    <a asp-controller="Language" asp-action="List" class="list-group-item"><i class="fas fa-language"></i> Language Options </a>       
</div>

WebUI/Views/Shared/_SearchBox.cshtml
<form class="form-inline my-2 my-lg-0" asp-action="Index" asp-controller="Book" method="get">
    <input id="q" name="q" type="text" class="form-control mr-sm-2" placeholder="Search">
    <button type="submit" class="btn btn-outline-light my-2 my-sm-0">Search</button>
</form>

WebUI/Views/Shared/_StatisticsMenu.cshtml
<div class="list-group">                    
    <a asp-controller="Statistics" asp-action="MonthChart" class="list-group-item"> Monthly book reading rate </a>            
    <a asp-controller="Statistics" asp-action="PieChart" class="list-group-item"> Reading rate by type </a>            
</div>

WebUI/Views/Shared/_UserPageMenu.cshtml
<div class="list-group">             
    <a asp-controller="User" asp-action="Read" class="list-group-item"> Unread </a>
    <a asp-controller="User" asp-action="Unread" class="list-group-item"> Readed </a>
    <a asp-controller="User" asp-action="Favorites" class="list-group-item"> Favorites </a>               
</div>